### ISSUE TITLE
主页面显示异常

### ISSUE THREAD

**Issue by MiaowFISH** [rain15z3/ClassTools#3]
天气挂件只显示温度，课表只有一节课
控制台并无报错
![捕获](https://user-images.githubusercontent.com/57578021/132952470-19aeab54-3e4e-425f-9f16-074ba3902bc4.PNG)
设置页面
![捕获](https://user-images.githubusercontent.com/57578021/132952419-6700b3d8-5eac-46f1-9129-37e682288bca.PNG)

**Comment by MiaowFISH** [comment]
课表是我的问题（捂脸
但天气挂件并不像示例那样显示其他信息

**Comment by luoling8192** [comment]
只显示温度这个是我改掉了，因为我觉得太占位置，以后打算换成其他的东西，暂时没有方法打开（

**Comment by luoling8192** [comment]
天气预报已经改回来了
